### ISSUE TITLE
Application Launch without voice input

### ISSUE THREAD

**Issue by BananaFish7** [nirmalpaul383/Project_Voice_Launcher#1]
In the project: Voice Launcher, when the listening is done without any voice input, Amazon application will launch by itself. The note in the notification tab for the voice launcher says : Launched " ". Nothing was said during the listening period yet Amazon keep launching by itself. I tried creating new If actions (if %gv_heard is set "_" then stop action) and (if %gv_heard is set Amazon then stop action) to counter it but nothing worked. How do I fix this error. 

https://user-images.githubusercontent.com/95184570/143780659-c88e6c5d-94f9-42a6-b8b1-3c545c0e07cb.mp4

**Comment by nirmalpaul383** [comment]
Dear @BananaFish7 ,
            Thank you for letting me know about this issue. This issue has been fixed in the latest version v1.0.1 . You can checkout the latest version of this project.

https://user-images.githubusercontent.com/40243913/144986424-e014d447-b03f-413c-83c5-85fe23b177e1.mp4

**Comment by BananaFish7** [comment]
https://user-images.githubusercontent.com/95184570/144991198-54e94870-8860-4b5b-af71-1993578f1789.mp4
