### ISSUE TITLE
Issue with v1.0.1 The Voice_Launcher

### ISSUE THREAD

**Issue by BananaFish7** [nirmalpaul383/Project_Voice_Launcher#2]
Although an attempt to fix the initial error was made but now the issue developed into going straight to "sorry! But could not hear anything from you" without any listening timeout.

https://user-images.githubusercontent.com/95184570/144991742-7f911dc3-6dea-4e64-9ae9-e097256eaea5.mp4

**Comment by nirmalpaul383** [comment]
Dear @BananaFish7 , 
          It looks like the Voice Launcher application is unable to access the device's microphone. There may have two main reasons for this:
1. Voice Launcher does not have the permission to access the microphone (As shown in the video).
2. Another application is accessing the microphone at the same time.

https://user-images.githubusercontent.com/40243913/145157099-64342cf5-4f7c-421b-b256-fa3dfb5c49f6.mp4
